//커널로서 사용되야 하는 함수는 "#pregma kernel"이라는 키워드를 통해 구별한다.
#pragma kernel GPU_TestFunctionA

//컴퓨트 셰이더의 실행결과를 저장할 버퍼를 선언한다
RWStructuredBuffer<float4> intBuffer;

//CPU에서 해당 컴퓨트 셰이더에 임의의 값을 전달하고 싶은 경우 일반적인 방법으로 변수를 선언 할 수 있으며. CPU스크립트에선
//해당 변수에 접근해, 값을 전달한다
int intValue;

[numthreads(8,8,1)]
void GPU_TestFunctionA (uint3 id : SV_DispatchThreadIDk, uint3 groupThreadID : SV_GroupThreadID)
{
    //함수 인자값에 대한 설명
    //컴퓨트셰이더에서 구현되는 커널함수의 인수에는 제약이 있다
    //일반적인 CPU프로그래밍과 비교하면 자유도가 낮다
    //:을 기준으로 오른쪽에 인수에 대한 설정을한다. 이를 시멘틱스라부름(강제)
    //:을 기준으로, 왼쪽 변수명으로써 자유롭게 선언 가능
    //:을 기준으로, 오른쪽은 미리 정의된 컴퓨트 셰이더에 정의된 유혛만 사용가능.
    intBuffer[groupThreadID.x] = groupThreadID.x * intValue;
}
